version: '3.8'
services:
  mtproto:
    image: telegrammessenger/proxy
    container_name: mtproto
    ports:
      - '8843:443'
    restart: always
    volumes:
      - './proxy-config:/data'
  l2tp:
    image: hwdsl2/ipsec-vpn-server
    container_name: l2tp
    ports:
      - '500:500/udp'
      - '4500:4500/udp'
    volumes:
      - './ikev2-vpn-data:/etc/ipsec.d'
    env_file: vpn.env
    restart: always
    privileged: true
